Add Ubuntu 24.10 Oracular Oriole
adoptium/installer pull request #1075
Opened 2024-12-16 11:24 UTC by Mailaender

https://canonical.com/blog/canonical-releases-ubuntu-24-10-oracular-oriole

2024-12-17 00:19 UTC, karianna commented
I don't _think_ we are supporting non LTS releases. labelling for PMC.

2024-12-17 10:13 UTC, Mailaender commented
It says
https://github.com/adoptium/installer/blob/0b7c92ab49b962fbb1b1d01e3062ab4b67aaf9f7/linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java#L34
and there are also remnants of the last STS version in the files.

2024-12-18 14:43 UTC, tellison commented
Discussed in the PMC call today. @steelhead31 will provide updates.

2024-12-18 14:59 UTC, steelhead31 commented
I've taken a look at this, and will attempt to get this done this week. Im currently improving our release process for linux packages, and would like to get this merged before I complete my work, so that I can include this.  Once the checks are running green, we can merge this PR. An additional PR is needed to be able to publish the packages to artifactory for this new version, which I'll take care of as soon as Im able.

2024-12-18 15:15 UTC, steelhead31 requested changes

2024-12-18 15:15 UTC, steelhead31 commented on linux/Jenkinsfile
> +            "oracular"  // Ubuntu/24.10 (STS)
Missing , at end of "oracular"

2024-12-18 15:58 UTC, steelhead31 commented
Im currently working on a PR that will fix the 2 failing actions JDK/JRE8 for alpine, the issue is not related to this PR, see : #1084

2024-12-18 20:31 UTC, karianna approved these changes

2024-12-19 09:08 UTC, steelhead31 approved these changes
Looks good.

2024-12-19 09:34 UTC, merged

2024-12-19 09:45 UTC, steelhead31 commented
PR for package republish is here : #1085

2024-12-20 09:53 UTC, steelhead31 commented
PR has been merged, I'll be building and pushing the packages up to artifactory throughout today.

2024-12-20 11:51 UTC, steelhead31 commented
DEBs for JDK8 have all been pushed.