Update README.md
adoptium/installer pull request #304
Opened 2021-04-01 12:19 UTC by 2001asjad

Added steps to describe how we put together deb and rpms in the README file.

Fixes #117

2021-04-01 12:23 UTC, karianna commented
@2001asjad You'll need to sign the Eclipse Contributor Agreement (Follow your nose from https://www.eclipse.org/legal/ECA.php).

2021-04-01 12:38 UTC, karianna requested changes
Change this to a simple link to the README.md file under the linux sub folder :0-)

2021-04-01 12:43 UTC, 2001asjad commented
> Change this to a simple link to the README.md file under the linux sub folder :0-)

Sorry I am a bit confused. Can you please explain me a bit more about it. Thanks

2021-04-01 12:57 UTC, karianna commented on README.md
> +3. To install `.deb` file via Command Line, follow these steps:
You can replace all of this with something like `3. [linux/README.md](Linux)`

2021-04-02 04:07 UTC, 2001asjad commented
@karianna addressed the changes, please take a look.
Thanks

2021-04-05 20:52 UTC, karianna approved these changes
lgtm

2021-04-05 20:52 UTC, merged