test: update tests for checking if rpm is signed when we use -PGPG_KEY
adoptium/installer pull request #514
Opened 2022-08-02 14:02 UTC by zdtsw

Ref: https://github.com/adoptium/installer/issues/513

2022-08-04 13:04 UTC, karianna requested changes
small type updates

2022-08-04 13:04 UTC, karianna commented on linux/jdk/redhat/build.gradle
> +		println "We set gpg!"
```suggestion
		println "We set the gpgkey!"
```

2022-08-04 13:04 UTC, karianna commented on linux/jdk/suse/build.gradle
> +		println "We set gpg!"
```suggestion
		println "We set the gpgkey!"
```

2022-08-11 05:47 UTC, zdtsw commented
@smlambert can I get a review on this PR?

2022-08-11 21:23 UTC, karianna approved these changes

2022-08-12 13:20 UTC, merged