fix: add sleep and this fixed problem of error when upload
adoptium/installer pull request #553
Opened 2022-11-07 11:56 UTC by zdtsw

- error: "No files were affected in the upload process"
	- could be when build just done jenkins not find archived file
	- could also be low performance in the server side to return code if it is after the first successful upload

2022-11-07 12:54 UTC, karianna requested changes
I think you should add comments on each line say why you added the sleep

2022-11-07 13:10 UTC, karianna approved these changes
Worth a try

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +        workaround for error when upload to artifactory: No files were affected in the upload process
```suggestion
        sleep is a workaround for error when upload to artifactory: No files were affected in the upload process
```

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +        workaround for error when upload to artifactory: No files were affected in the upload process
```suggestion
        sleep is a workaround for error when upload to artifactory: No files were affected in the upload process
```

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +                /*
```suggestion
                  /*
```

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +                    workaround for error when upload to artifactory: No files were affected in the upload process
```suggestion
                      sleep is a workaround for error when upload to artifactory: No files were affected in the upload process
```

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +                    might be caused by 1) slow response from artifactory server 2) archive just done by jenkins job
```suggestion
                      might be caused by 1) slow response from artifactory server 2) archive just done by jenkins job
```

2022-11-07 13:10 UTC, karianna commented on linux/Jenkinsfile
> +                */
```suggestion
                  */
```

2022-11-09 13:49 UTC, karianna approved these changes
LGTM

2022-11-09 14:50 UTC, zdtsw commented
> Do we have an issue opened for the error mentioned in this PR? It might be worth to find out the root cause of the error instead of pushing this PR, which might not be the fix?

I do not have an issue created, only posted it on the slack channel, but I can create one.

I have used this branch to publish for jdk11, 17 and 19, all worked well. (at least I do not see problem failed to upload)

2022-11-09 14:56 UTC, zdtsw commented
add issue for tracking purpose: https://github.com/adoptium/installer/issues/554

2022-11-14 16:38 UTC, sophia-guo commented
Talked with @zdtsw to make sure this is the right solution we'd like to rerun the job and list/query the archived artifacts right after the buildAndTest() to see if it's possible that no artifacts are available after the step buildAndTest().

2022-11-14 18:51 UTC, zdtsw commented
from the test job, it did show by query artifacts from build, it has these rpms created
see log: https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/84/console
and the content.txt file:  https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/84/execution/node/3/ws/linuxSuse/content.txt


but from source of this plugin (which has not been changed for 4yrs) https://github.com/jenkinsci/artifactory-plugin/blame/master/src/main/java/org/jfrog/hudson/pipeline/common/executors/GenericUploadExecutor.java#L58
is `List<Artifact> deployedArtifacts` did not get any file returned

2022-11-15 08:39 UTC, zdtsw commented
this is another test: based on master( without sleep) but removed archive step
https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_NEW/87/console

Not see error with `No files were affected in the upload process` 
(ignore the before because artifactory is set to deny overwritten, so we wont really get the upload done to jdk11 suse again)

2022-11-15 08:45 UTC, zdtsw commented
Question:  what is the reason we do archive? looks like this is the problem and also archive took time (3m-4m) for all platforms in suse.   cannot we just upload from the workspace? 
the pattern is already set to `"pattern": "**/build/ospackage/*.${entry.value}.rpm", `for rpm
`pattern": "**/build/ospackage/temurin-*${debArchList[buildArch]}.deb" `for deb
`"pattern": "**/build/ospackage/temurin-*.apk",` for apk

2022-11-17 12:01 UTC, zdtsw commented
did another test on master branch (no sleep)
https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/181/console 
with consistent error as saw at first.
```
java.lang.RuntimeException: Fail-no-op: No files were affected in the upload process.
	at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:59)
	at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:39)
	at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:24)
```

2022-11-18 07:58 UTC, zdtsw commented
updated with solution: not just use sleep , instead doing checking existence first then sleep and loop

2022-11-22 06:35 UTC, merged