Issue/417
adoptium/installer pull request #623
Opened 2023-03-01 11:35 UTC by chandrashritii

*Description* 

Update Temurin spec | Linux

This PR fixes https://github.com/adoptium/installer/issues/417

Signed-off-by: Shriti Chandra [shchandr@redhat.com](mailto:shchandr@redhat.com)

2023-03-01 19:58 UTC, karianna commented
@chandrashritii you'll need to sign the Eclipse Foundation CLA

2023-03-01 20:50 UTC, jiekang requested changes
Thanks Shriti!

Please also increment the `spec_release` field [1] and add a changelog entry for the spec files. Changes that alter the result needs an incremented `spec_release` so users can upgrade to it properly.

The changelog entry can be a short description of the fix you're making, for example 'Fix alternatives linking'



[1]
https://github.com/adoptium/installer/blob/19f2f00c8655a3db4707f8b418fa621e6c1db002/linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec#L8

[2]
https://github.com/adoptium/installer/blob/19f2f00c8655a3db4707f8b418fa621e6c1db002/linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec#L265

2023-03-02 12:14 UTC, chandrashritii commented
Thanks for the review! @jiekang Added the necessary changelogs

2023-03-02 15:15 UTC, jiekang requested changes

2023-03-02 15:17 UTC, jiekang commented on linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
> +* Thu March 2 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 11.0.18.0.0.10.adopt0
I think it's fine to remove 'Draft' status after confirming ECA and these last changes.

2023-03-15 11:28 UTC, jiekang approved these changes

2023-03-15 11:31 UTC, jiekang commented
@chandrashritii There are still two commits with an unknown author/email address. You will need to modify those for the ECA check to pass. I recommend using `git rebase -i` and making this a single commit with your changes on top of the latest `adoptium:master` commit.

2023-03-15 11:32 UTC, jiekang commented
Specifically:

https://github.com/adoptium/installer/pull/623/commits/eb2dac66d5b14531339d974fec6da75d0050ffea
https://github.com/adoptium/installer/pull/623/commits/3614035b76532236ec45bd2cb64101e8b8ad5e4e

2023-04-04 07:23 UTC, karianna commented
https://stackoverflow.com/questions/34850831/change-git-email-for-previous-commits may help

2023-04-04 11:42 UTC, gdams commented
This will also need updating to include the recently added JDK20 config files

2023-04-06 09:19 UTC, karianna commented
@chandrashritii will need a rebase

2023-04-13 00:00 UTC, karianna approved these changes

2023-04-13 05:35 UTC, karianna commented
@chandrashritii getting close, just some errors in the changelog format, see the failing GH Actions

2023-04-16 17:42 UTC, chandrashritii commented
Thanks! @karianna Fixed the changelog format

2023-04-17 14:00 UTC, jiekang commented on linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
> +<<<<<<< HEAD
@chandrashritii Looks like the merges need to be resolved here and in a few of the other files.

2023-04-23 07:19 UTC, karianna commented
SUSE jobs still failing but no clear reason as to why

2023-04-28 15:36 UTC, jiekang commented
I think the jdk 19 jobs fail due to the ExclusiveArch check in build.sh not accounting for specs without that field. However we can drop the changes to the 19 specs as 20 is out and ignore them.

2023-04-29 00:53 UTC, karianna commented
@jiekang Will need a rebase now sorry :-(

2023-05-04 07:25 UTC, karianna commented
Still have failing SUSE jobs...

2023-05-18 11:51 UTC, jiekang commented
/thaw

2023-05-18 12:29 UTC, steelhead31 approved these changes
LGTM

2023-05-18 19:45 UTC, merged