Add all files from source packages to target APK
adoptium/installer pull request #625
Opened 2023-03-05 17:05 UTC by ascheman

Add all files from source packages to target APK
and remove "virtual package" from dependencies as it is empty now.

Resolves #613

Should be tested in the context of mercedes-benz/sechub#1794 // @Jeeppler + @ryanlewis

2023-03-06 09:56 UTC, Jeeppler commented
@ascheman is this pull-request ready to be tested?

2023-03-06 10:00 UTC, ascheman commented
> @ascheman is this pull-request ready to be tested?

Yes, please test it, @Jeeppler - As soon as you come back with a positive result I will make it official (remove Draft status).

2023-03-06 18:10 UTC, Jeeppler commented
@ascheman 

Tested with SecHub 0.37.0 (Spring Boot 2.7.6) on Alpine Image:

- Temurin 8: SecHub cannot be build with Java 8
- Temurin 11: 
  - temurin-11-jre-11.0.18_p10-r0.apk -> works
  - temurin-11-jdk-11.0.18_p10-r0.apk -> works
- Temurin 17: 
  - temurin-17-jre-17.0.6_p10-r0.apk -> works
  - temurin-17-jdk-17.0.6_p10-r0.apk -> works
- Temurin 19: 
  - temurin-19-jre-19.0.2_p7-r0.apk -> works
  - temurin-19-jdk-19.0.2_p7-r0.apk -> works

RESULT: All conducted tests were successful. Temurin 11, 17 and 19 work for both JDK and JRE packages.

NOTES: I can see the following warning in the test section:

~~~
>>> WARNING: temurin-11*: No arch specific binaries found so arch should probably be set to "noarch"
~~~

2023-03-06 20:46 UTC, ascheman commented
> Tested with SecHub 0.37.0 (Spring Boot 2.7.6) on Alpine Image:
> 
> * Temurin 8: SecHub cannot be build with Java 8
> * Temurin 11:
>   
>   * temurin-11-jre-11.0.18_p10-r0.apk -> works
>   * temurin-11-jdk-11.0.18_p10-r0.apk -> works
> * Temurin 17:
>   
>   * temurin-17-jre-17.0.6_p10-r0.apk -> works
>   * temurin-17-jdk-17.0.6_p10-r0.apk -> works
> * Temurin 19:
>   
>   * temurin-19-jre-19.0.2_p7-r0.apk -> works
>   * temurin-19-jdk-19.0.2_p7-r0.apk -> works
> 
> RESULT: All conducted tests were successful. Temurin 11, 17 and 19 work for both JDK and JRE packages.

Thanks for testing @Jeeppler 

> NOTES: I can see the following warning while building the temurin packages via gradle:
> 
> ```
> >>> WARNING: temurin-11*: No arch specific binaries found so arch should probably be set to "noarch"
> ```

I could avoid this warning with my latest change (d38b818).
Nevertheless there are more `WARNING`s and even `ERROR`s during the build, e.g., since Alpine JDKs do not contain `libawt.so`.

2023-03-07 12:03 UTC, Jeeppler commented
If you set the architecture to `x86_64` it will probably not work if the architecture is different. It should be possible to compile/build the JRE and JDK packages for other architectures as well. 

Is there no variable for the architecture which you can use/set during the build?

2023-03-07 12:42 UTC, ascheman commented
> If you set the architecture to `x86_64` it will probably not work if the architecture is different. It should be possible to compile/build the JRE and JDK packages for other architectures as well.
> 
> Is there no variable for the architecture which you can use/set during the build?

To my understanding, there is only `x86_64` for Alpine, and it was configured for this arch the hard way anyways (cf. eg., https://github.com/adoptium/installer/blob/8687b392feaeb2cab9b72ab780d6d673ab81609a/linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD#L12).

2023-03-07 20:45 UTC, smlambert commented
[Project Management Committee](https://www.eclipse.org/projects/dev_process/#4_6_1_PMC) - all Eclipse Foundation top-level projects, including Adoptium has a PMC that is responsible for technical guidance of the project. (Documentation on Dev process [Leadership](https://www.eclipse.org/projects/dev_process/#4_6_Leaders) at Eclipse Foundation).

2023-03-10 08:30 UTC, steelhead31 requested changes
Can you also include this fix into the JDK & JRE 20 versions please?, these were merged yesterday, otherwise LGTM.

2023-03-10 08:37 UTC, steelhead31 approved these changes
LGTM, issue #631 has been raised to cover replicating this fix for JDK20.

2023-03-11 00:33 UTC, karianna approved these changes
I'm assuming noarch as this is to do with docs?

2023-03-12 10:32 UTC, gdams approved these changes

2023-03-13 03:36 UTC, merged