jdk-17 April 2023 PSU Installers
adoptium/installer pull request #660
Opened 2023-04-26 15:26 UTC by andrew-m-leonard

2023-04-26 15:39 UTC, steelhead31 requested changes
Spec version should be reset.

2023-04-26 15:39 UTC, steelhead31 commented on linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
> +%global spec_release 4
This should be 1 as its the first spec version of 17.0.7

2023-04-26 15:39 UTC, steelhead31 commented on linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
> +- Eclipse Temurin 17.0.7+7 release 4.
Again, this should be release 1.

2023-04-26 15:39 UTC, steelhead31 commented on linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
> +%global spec_release 3
spec release 1 as this is the first version of this package

2023-04-26 15:39 UTC, steelhead31 commented on linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
> +- Eclipse Temurin 17.0.7+7 release 3.
release 1.

2023-04-26 15:39 UTC, steelhead31 commented on linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
> +%global spec_release 4
spec release 1

2023-04-26 15:39 UTC, steelhead31 commented on linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
> +- Eclipse Temurin JRE 17.0.7+7 release 4.
release 1.

2023-04-26 15:39 UTC, steelhead31 commented on linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec
> +%global spec_release 3
should be spec\_release 1

2023-04-26 15:39 UTC, steelhead31 commented on linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec
> +- Eclipse Temurin JRE 17.0.7+7 release 3.
should be release 1.

2023-04-26 17:23 UTC, steelhead31 approved these changes
LGTM!

2023-04-26 19:26 UTC, karianna approved these changes

2023-04-27 15:10 UTC, andrew-m-leonard commented
/merge

2023-04-27 15:11 UTC, gdams commented
/approve

2023-04-27 15:13 UTC, tellison approved these changes

2023-04-27 15:14 UTC, tellison commented
/approve

2023-04-27 17:25 UTC, merged