feat: add support for fedora38 installer
adoptium/installer pull request #673
Opened 2023-05-15 01:31 UTC by zdtsw

Ref: https://github.com/adoptium/adoptium/issues/233

2023-05-15 10:51 UTC, karianna requested changes

2023-05-16 23:08 UTC, zdtsw commented on .github/workflows/linux.yml
> +      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.8.0
GitHub UI "uppdate branch" did a merge from master to my branch instead of rebasing. 
I will do a local cleanup and force a new commit

2023-05-17 01:37 UTC, karianna approved these changes

2023-05-26 10:44 UTC, gdams approved these changes

2023-05-26 10:45 UTC, merged