Installers: Add Base Installer Files Ahead Of JDK21 release.
adoptium/installer pull request #735
Opened 2023-09-18 08:14 UTC by steelhead31

DO NOT MERGE UNTIL CHECKSUMS ARE CORRECT  
  
Add the initial base files which will require the usual filename, checksum and version number updates during the release.

Fixes #736

2023-09-18 08:17 UTC, steelhead31 commented
Checks fail, as the binary files are not present yet.

2023-09-18 12:02 UTC, adamfarley commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +source="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-$_pkgvername/OpenJDK21U-jdk_x64_alpine-linux_hotspot_$_pkgver.tar.gz
Is the "U" correct, prior to October?

2023-09-18 12:03 UTC, adamfarley commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +_java_home="/usr/lib/jvm/java-19-temurin"
Should this be jdk20?

2023-09-18 12:04 UTC, adamfarley commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +b03aced4b7a1c49bc00297e35e45480fd03818862b93e17e1551a3b721e89306  OpenJDK21U-jdk_x64_alpine-linux_hotspot_$_pkgver.tar.gz
Another "U".

2023-09-18 12:07 UTC, adamfarley commented on linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
> +amd64_tarball_url = https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.0%2B35/OpenJDK21U-jdk_x64_linux_hotspot_21.0.0_35.tar.gz
"U"

2023-09-18 12:07 UTC, adamfarley commented on linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
> +arm64_tarball_url = https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.0%2B35/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.0_35.tar.gz
"U"

2023-09-18 12:10 UTC, adamfarley commented on linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
> +Source1: %{source_url_base}/jdk-%{upstream_version_url}/OpenJDK21U-jdk_%{vers_arch}_linux_hotspot_%{upstream_version_no_plus}.tar.gz.sha256.txt
"U"

Also, I'm going to stop tagging all the "U"s. There's a bunch more of them, and the million one-letter-comments doesn't add value.

2023-09-18 12:12 UTC, adamfarley requested changes
A few points to consider. Once addressed (fixed/justified), will approve.

2023-09-18 12:14 UTC, steelhead31 commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +_java_home="/usr/lib/jvm/java-19-temurin"
Yup, fixed!

2023-09-18 12:14 UTC, steelhead31 commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +b03aced4b7a1c49bc00297e35e45480fd03818862b93e17e1551a3b721e89306  OpenJDK21U-jdk_x64_alpine-linux_hotspot_$_pkgver.tar.gz
Yup, fixed!

2023-09-18 12:14 UTC, steelhead31 commented on linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
> +arm64_tarball_url = https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.0%2B35/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.0_35.tar.gz
Yup, fixed!

2023-09-18 12:14 UTC, steelhead31 commented on linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
> +Source0: %{source_url_base}/jdk-%{upstream_version_url}/OpenJDK21U-jdk_%{vers_arch}_linux_hotspot_%{upstream_version_no_plus}.tar.gz
Yup, fixed!

2023-09-18 12:18 UTC, adamfarley approved these changes
LGTM :)

2023-09-19 01:00 UTC, karianna requested changes

2023-09-19 08:17 UTC, steelhead31 commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +_java_home="/usr/lib/jvm/java-20-temurin"
Fixed

2023-09-19 08:19 UTC, steelhead31 commented on linux/Jenkinsfile
> +        choice(name: 'VERSION', choices: ['8', '11', '17', '20', '21'], description: 'Build for specific JDK VERSION')
Removed JDK20 :)

2023-09-19 08:23 UTC, steelhead31 commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +provider_priority=21
I think its correct, all of the previous versions of the APKBUILD file have the provider priority set as the JDK version, @gdams can you confirm ?

2023-09-19 08:24 UTC, steelhead31 commented on linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
> +priority = 2100
I've updated this to match the previous debian version, ie 1112 for JDK11, 1712 for JDK17 etc.

2023-09-19 14:25 UTC, gdams commented on linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
> +provider_priority=21
Yeah looking at how the community do this for Alpine we are doing the same which makes sense https://git.alpinelinux.org/aports/tree/community/openjdk17/APKBUILD?h=3.15-stable

2023-09-20 04:41 UTC, karianna approved these changes

2023-09-20 08:02 UTC, steelhead31 commented
DO NOT MERGE UNTIL CHECKSUMS ARE CORRECTED FOR RELEASE

2023-10-06 13:46 UTC, steelhead31 commented on linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
> +* Wed Sep 20 2023 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 21.0.0.0.0.35-0
Fixed, thanks!

2023-10-11 18:51 UTC, gdams commented
@steelhead31 we've started publishing the binaries now. Can you update the shasums?

2023-10-11 19:26 UTC, gdams commented
/thaw

2023-10-12 17:45 UTC, gdams commented on linux/jdk/debian/src/main/packaging/temurin/21/debian/control
> +Architecture: amd64 armhf arm64 ppc64el s390x
```suggestion
Architecture: amd64 arm64 ppc64el
```

2023-10-12 17:56 UTC, jiekang approved these changes
Specs look fine to me. Would be nice if the GH check could test them. Wonder if it's worthwhile in making the specs usable when not all arches are available... but for a separate conversation

2023-10-12 19:55 UTC, gdams commented on linux/jre/debian/src/main/packaging/temurin/21/debian/control
> +Architecture: amd64 armhf arm64 ppc64el s390x
```suggestion
Architecture: amd64 arm64 ppc64el
```

2023-10-12 22:05 UTC, gdams approved these changes
LGTM (subject to ppc64le either being removed or waiting until it's been shipped)

2023-10-13 08:17 UTC, merged